version: 2
updates:
  - package-ecosystem: github-actions
    assignees:
      - Rakambda
    schedule:
      interval: daily
      time: '05:00'
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
